import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Google_Sans,
  Google_Sans_Flex,
  Inter,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Laptop Rental Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${googleSans.variable} ${googleSansFlex.variable} font-google-sans-flex antialiased px-2 md:px-4 lg:px-6 py-2`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
